config/routes.rb
Rails.application.routes.draw do
  get 'payments/index'
  get 'payments/pay'
  get 'payment/index'
  get 'payment/pay'
  devise_for :users
  
  root "home#index"
  
  resources :products do
    resources :reviews
  end

  resources :lineitems
  
  resource :carts, only: [:show]
  
  

  resources :orders do
      member do
        get :shipped        
        get :being_packed
        get :complete
        get :cancel
      end
  end

  #get '/orders/:id', to: 'orders#cancel' , as: 'order'
  
  resources :payments

 
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
  validates_presence_of :address_1, :address_2, :city, :state, :country, :postal_code
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :lineitems, dependent: :destroy 
  has_many :products, through: :lineitems
  
  def sub_total
    sum = 0
    self.lineitems.each do |lineitem|
      sum+= lineitem.total_price
    end
    return sum
  end
end

app/models/lineitem.rb
class Lineitem < ApplicationRecord
  belongs_to :order
  belongs_to :product
  before_save :set_unit_price
  before_save :set_total_price

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

  private

  def set_unit_price
    self[:unit_price] = unit_price
  end
  
  def set_total_price
    self[:total_price] = quantity * set_unit_price
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
	has_many :lineitems, dependent: :destroy
  has_one :payment
	before_save :set_subtotal
  after_commit :assign_default_status

  enum status: %i[processing shipped being_packed complete cancelled]

	def subtotal
		lineitems.collect {|lineitem| lineitem.valid? ? (lineitem.unit_price*lineitem.quantity) : 0}.sum
	end

	private


	def set_subtotal
		self[:subtotal] = subtotal
	end

  def assign_default_status
    self.status = "processing"
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :lineitems
  belongs_to :user
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products
  has_many :orders
  has_many :reviews, dependent: :destroy
  has_one :address  
  accepts_nested_attributes_for :address
         
  after_create :assign_default_role

  def assign_default_role
    self.add_role(:buyer) if self.roles.blank?
  end

  def with_address
    build_address if address.nil?
    self
  end
  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @lineitems = current_order.lineitems
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all
    @lineitem = current_order.lineitems.new
  end  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = current_user.orders  
    if current_user.has_role? :seller
      @orders = Order.all
    end
  end

  def show
    @order = Order.all
  end

  def cancel
    @order = Order.find(params[:id])
    @order.cancelled!
    redirect_to orders_path
  end

  def shipped
    @order = Order.find(params[:id])
    @order.shipped!
    redirect_to orders_path
  end

  def being_packed
    @order = Order.find(params[:id])
    @order.being_packed!
    redirect_to orders_path
  end

  def complete
    @order = Order.find(params[:id])
    @order.complete!
    redirect_to orders_path
  end

  private

  def payments_params
    params.require(:order).permit(:status)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_order    
    if user_signed_in?
      @order = current_user.orders.last
      if @order.nil?
        @order = Order.new
      elsif @order.status == "processing"
        @order
      else
        Order.new      
      end
    elsif !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lineitems_helper.rb
module LineitemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payment_helper.rb
module PaymentHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/carts/_cart_item.html.erb
<% if !@lineitem.nil? && @lineitem.errors.any? %>
	<ul>
		<% @lineitem.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>

<% if @lineitems.size>0 %>
<div class="row row-cols-1 row-cols-md-3 g-4">
	<% @lineitems.each do |item| %>
  <div class="col">
    <div class="card h-100">
      <img src="https://mdbcdn.b-cdn.net/img/new/standard/city/044.webp" class="card-img-top" alt="Skyscrapers"/>
      <div class="card-body">
        <h5 class="card-title"><%= item.product.title %></h5>
        <p class="card-text"><%=item.product.description%></p>
      </div>
      <%= form_for(item, remote: true) do |f| %>
        <%= f.hidden_field :product_id, value: item.product.id %>
        <%= f.hidden_field :user_id, value: current_user %>
        <div class="card-footer">
          <h5><%= item.product.price %></h5>
          <%= f.number_field :quantity, value: item.quantity.to_i, min: 1, class: 'form-control' %>
          <div class="btn-group">
            <%= f.submit "Update Quantity", class: 'btn btn-primary' %>
          <% end %>
          <div>
            <%= button_to "Remove", item, method: :delete, remote: true, class: 'btn btn-danger'  %>
          </div>
          </div>
            <br>
          <strong>Total Price: <%= item.total_price %></strong>
        </div>
      </div>
    </div>	
  <% end %>
</div>
<div>
  <%= link_to "Add More item to cart", root_path %><br>
  <%= link_to "Price: #{current_order.subtotal}", carts_path %><br>
  <%= link_to "Proceed to checkout", new_payment_path  %>
</div>
<% end %>
	

app/views/carts/show.html.erb
<div class="cart_item">
	<%= render "carts/cart_item" %>
</div>

app/views/orders/index.html.erb
<h2>All Orders</h2>
<% if current_user.has_role? :seller %>
  <div>
    Total Order Count <%= Order.count %><br>
    Total revenue generated <%= Order.sum(:subtotal)%>
  </div>
<% end %>

<% @orders.each do |order| %>
  <p>Order Id: <%= order.id %></p>
  <p>Line Items: </p>
  <ul>
    <% order.lineitems.each do |item| %>
    <li><%= item.quantity %> x <%= item.product.title %></li>
    <% end %>
  </ul>
  <p>Order status: <%= order.status %></p>
  <p>Payment id: <%= order.payment%></p>
  <% if order.status == "shipped" %>
    <%= link_to 'Cancel order', cancel_order_path(order) %>
  <% end %>
  <% if current_user.has_role? :seller %>
    <div>
      <%= link_to 'shipped', shipped_order_path(order) %>
      <%= link_to 'being packed', being_packed_order_path(order) %>
      <%= link_to 'complete', complete_order_path(order) %>
    </div>
  <% end %>
<% end %>