config/routes.rb
Rails.application.routes.draw do
  get 'payments/index'
  get 'payments/pay'
  get 'payment/index'
  get 'payment/pay'
  devise_for :users
  
  root "home#index"
  
  resources :products do
    resources :reviews
  end

  resources :lineitems
  
  resource :carts, only: [:show]
  
  

  resources :orders do
      member do
        get :shipped        
        get :being_packed
        get :complete
        get :cancel
      end
  end

  #get '/orders/:id', to: 'orders#cancel' , as: 'order'
  
  resources :payments

 
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
  validates_presence_of :address_1, :address_2, :city, :state, :country, :postal_code
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :lineitems, dependent: :destroy 
  has_many :products, through: :lineitems
  
  def sub_total
    sum = 0
    self.lineitems.each do |lineitem|
      sum+= lineitem.total_price
    end
    return sum
  end
end

app/models/lineitem.rb
class Lineitem < ApplicationRecord
  belongs_to :order
  belongs_to :product
  before_save :set_unit_price
  before_save :set_total_price

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

  private

  def set_unit_price
    self[:unit_price] = unit_price
  end
  
  def set_total_price
    self[:total_price] = quantity * set_unit_price
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
	has_many :lineitems, dependent: :destroy
  has_one :payment
	before_save :set_subtotal
  after_commit :assign_default_status

  enum status: %i[processing shipped being_packed complete cancelled]

	def subtotal
		lineitems.collect {|lineitem| lineitem.valid? ? (lineitem.unit_price*lineitem.quantity) : 0}.sum
	end

	private


	def set_subtotal
		self[:subtotal] = subtotal
	end

  def assign_default_status
    self.status = "processing"
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :lineitems
  belongs_to :user
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products
  has_many :orders
  has_many :reviews, dependent: :destroy
  has_one :address  
  accepts_nested_attributes_for :address
         
  after_create :assign_default_role

  def assign_default_role
    self.add_role(:buyer) if self.roles.blank?
  end

  def with_address
    build_address if address.nil?
    self
  end
  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @lineitems = current_order.lineitems
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all
    @lineitem = current_order.lineitems.new
  end  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = current_user.products.all
  end  

  def show
    @product = Product.find(params[:id])
    @review = Review.new
  end

  def new
    @product = current_user.products.new
  end

  def create
    @product = current_user.products.build(product_params)
    if @product.save
      redirect_to products_path
    else
      render 'new'
    end
  end

  def edit
    @product = current_user.products.find(params[:id])
  end

  def update
    @product = current_user.products.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
    else
      render 'edit'
    end
  end

  def destroy
    @product = current_user.products.find(params[:id])
    @product.destroy
    redirect_to products_path
  end
  
  private

  def product_params
    params.require(:product).permit(:title, :description, :price, :user_id, :current_user)    
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_order    
    if user_signed_in?
      @order = current_user.orders.last
      if @order.nil?
        @order = Order.new
      elsif @order.status == "processing"
        @order
      else
        Order.new      
      end
    elsif !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lineitems_helper.rb
module LineitemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payment_helper.rb
module PaymentHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
	<div class="form-group">
		<%= f.label :title, "Title" %>
		<%= f.text_field :title, class: 'form-control' %>
	</div>

  <div class="form-group">
		<%= f.label :description, "description" %>
		<%= f.text_field :description, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :price, "Price" %>
		<%= f.number_field :price, value: 1, class: 'form-control', min: 1 %>
	</div>

	<%= f.submit "Save", class: 'btn btn-success' %>
<% end %>
  

app/views/products/edit.html.erb
<h3>Update product</h3>

<%= render 'form' %>

app/views/products/index.html.erb
<% if current_user.has_role? :seller %>

<h1>Products</h1>

<%= link_to "New product", new_product_path %>
<%= link_to "all Orders", orders_path %>

<div class="col-md-6 col-md-offset-3">
	<table class="table">
		<thead>
			<tr>
				<th>Title</th>
				<th>Price</th>
				<th>Action</th>
			</tr>
		</thead>
		<tbody>
			<% @products.each do |product| %>
				<tr>
					<td><%= product.title %></td>
					<td><%= product.price %></td>
					<td>
						<%= link_to "Edit", edit_product_path(product) %>
						<%= button_to "Delete", product_path(product), method: :delete %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
  
</div>
<% else %>
  <h1>this page is only for seller</h1>
  <%= link_to "Back to Products", root_path %>
<% end%>

app/views/products/new.html.erb
<h3>Create new product</h3>

<%= render 'form' %>

app/views/products/show.html.erb
<div>
  <div class="card h-100">
      <img src="https://mdbcdn.b-cdn.net/img/new/standard/city/044.webp" class="card-img-top" alt="Skyscrapers"/>
  <h1><%= @product.title %></h1>
  <strong>Product description:</strong><p><%= @product.description %></p>
  <strong>Price:</strong><p><%= @product.price %></p>
  </div>
</div>

<h2>Product Reviews</h2>
<%= render @product.reviews %>

<h2>Add a comment:</h2>
<%= render 'reviews/form', product: @product, review: @review %>